# -*- coding: utf-8 -*-
"""Prak2_elkom 1 dan 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fhwub8AN53Std4IJIfaXDBaPxO9wAM-P
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
import math

def hitung_sisi_a(sisi_b, sisi_c):
    return math.sqrt(sisi_c**2 - sisi_b**2)

def hitung_sisi_b(sisi_a, sisi_c):
    return math.sqrt(sisi_c**2 - sisi_a**2)

def hitung_sisi_c(sisi_a, sisi_b):
    return math.sqrt(sisi_a**2 + sisi_b**2)

print("Kalkulator Pythagoras")
print("Pilih operasi:")
print("1. Hitung sisi a")
print("2. Hitung sisi b")
print("3. Hitung sisi c")
pilihan = int(input("Masukkan nomor operasi yang diinginkan (1/2/3): "))

if pilihan == 1:
    sisi_b = float(input("Masukkan panjang sisi b: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_b or sisi_b == sisi_c:
        if sisi_c < sisi_b:
            print("Nilai c tidak boleh lebih kecil dari nilai b.")
        else:
            print("Nilai b tidak boleh sama dengan nilai c.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_a = hitung_sisi_a(sisi_b, sisi_c)
    print(f"Panjang sisi a adalah: {sisi_a}")
elif pilihan == 2:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_a or sisi_a == sisi_c:
        if sisi_c < sisi_a:
            print("Nilai c tidak boleh lebih kecil dari nilai a.")
        else:
            print("Nilai a tidak boleh sama dengan nilai c.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_b = hitung_sisi_b(sisi_a, sisi_c)
    print(f"Panjang sisi b adalah: {sisi_b}")
elif pilihan == 3:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_b = float(input("Masukkan panjang sisi b: "))
    while sisi_b == sisi_a or sisi_b == sisi_c:
        print("Nilai b tidak boleh sama dengan nilai a atau c.")
        sisi_b = float(input("Masukkan ulang panjang sisi b: "))
    sisi_c = hitung_sisi_c(sisi_a, sisi_b)
    print(f"Panjang sisi c adalah: {sisi_c}")
else:
    print("Pilihan operasi tidak valid. Harap masukkan 1, 2, atau 3.")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
import math

def hitung_sisi_a(sisi_b, sisi_c):
    return math.sqrt(sisi_c**2 - sisi_b**2)

def hitung_sisi_b(sisi_a, sisi_c):
    return math.sqrt(sisi_c**2 - sisi_a**2)

def hitung_sisi_c(sisi_a, sisi_b):
    return math.sqrt(sisi_a**2 + sisi_b**2)

print("Kalkulator Pythagoras")
print("Pilih operasi:")
print("1. Hitung sisi a")
print("2. Hitung sisi b")
print("3. Hitung sisi c")
pilihan = int(input("Masukkan nomor operasi yang diinginkan (1/2/3): "))

if pilihan == 1:
    sisi_b = float(input("Masukkan panjang sisi b: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_b or sisi_b == sisi_c:
        if sisi_c < sisi_b:
            print("Nilai c tidak boleh lebih kecil dari nilai b.")
        else:
            print("Nilai b tidak boleh sama dengan nilai c.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_a = hitung_sisi_a(sisi_b, sisi_c)
    print(f"Panjang sisi a adalah: {sisi_a}")
elif pilihan == 2:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_a or sisi_a == sisi_c:
        if sisi_c < sisi_a:
            print("Nilai c tidak boleh lebih kecil dari nilai a.")
        else:
            print("Nilai a tidak boleh sama dengan nilai c.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_b = hitung_sisi_b(sisi_a, sisi_c)
    print(f"Panjang sisi b adalah: {sisi_b}")
elif pilihan == 3:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_b = float(input("Masukkan panjang sisi b: "))
    while sisi_b == sisi_a or sisi_b == sisi_c:
        print("Nilai b tidak boleh sama dengan nilai a atau c.")
        sisi_b = float(input("Masukkan ulang panjang sisi b: "))
    sisi_c = hitung_sisi_c(sisi_a, sisi_b)
    print(f"Panjang sisi c adalah: {sisi_c}")
else:
    print("Pilihan operasi tidak valid. Harap masukkan 1, 2, atau 3.")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
import math

def hitung_sisi_a(sisi_b, sisi_c):
    return math.sqrt(sisi_c**2 - sisi_b**2)

def hitung_sisi_b(sisi_a, sisi_c):
    return math.sqrt(sisi_c**2 - sisi_a**2)

def hitung_sisi_c(sisi_a, sisi_b):
    return math.sqrt(sisi_a**2 + sisi_b**2)

print("Kalkulator Pythagoras")
print("Pilih operasi:")
print("1. Hitung sisi a")
print("2. Hitung sisi b")
print("3. Hitung sisi c")
pilihan = int(input("Masukkan nomor operasi yang diinginkan (1/2/3): "))

if pilihan == 1:
    sisi_b = float(input("Masukkan panjang sisi b: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_b or sisi_b == sisi_c:
        if sisi_c < sisi_b:
            print("Nilai c tidak boleh lebih kecil dari nilai b.")
        else:
            print("Nilai b tidak boleh sama dengan nilai c.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_a = hitung_sisi_a(sisi_b, sisi_c)
    print(f"Panjang sisi a adalah: {sisi_a}")
elif pilihan == 2:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_c = float(input("Masukkan panjang sisi c: "))
    while sisi_c < sisi_a or sisi_a == sisi_c:
        if sisi_c < sisi_a:
            print("Nilai c tidak boleh lebih kecil dari nilai a.")
        else:
            print("Nilai a tidak boleh sama dengan nilai c.")
        sisi_c = float(input("Masukkan ulang panjang sisi c: "))
    sisi_b = hitung_sisi_b(sisi_a, sisi_c)
    print(f"Panjang sisi b adalah: {sisi_b}")
elif pilihan == 3:
    sisi_a = float(input("Masukkan panjang sisi a: "))
    sisi_b = float(input("Masukkan panjang sisi b: "))
    while sisi_b == sisi_a or sisi_b == sisi_c:
        print("Nilai b tidak boleh sama dengan nilai a atau c.")
        sisi_b = float(input("Masukkan ulang panjang sisi b: "))
    sisi_c = hitung_sisi_c(sisi_a, sisi_b)
    print(f"Panjang sisi c adalah: {sisi_c}")
else:
    print("Pilihan operasi tidak valid. Harap masukkan 1, 2, atau 3.")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')
# Meminta input dari pengguna untuk tiga angka
angka1 = float(input("Masukkan angka pertama: "))
angka2 = float(input("Masukkan angka kedua: "))
angka3 = float(input("Masukkan angka ketiga: "))

# Menggunakan fungsi max() untuk menemukan angka terbesar
angka_terbesar = max(angka1, angka2, angka3)

# Menampilkan angka terbesar
print(f"Angka terbesar adalah: {angka_terbesar}")